//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelimundoERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCentro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCentro()
        {
            this.catBusquedaCentro = new HashSet<catBusquedaCentro>();
        }
    
        public System.Guid CentroID { get; set; }
        public Nullable<int> TipoCentroID { get; set; }
        public int LicenciaID { get; set; }
        public string CodigoCentro { get; set; }
        public string Nombre { get; set; }
        public string email { get; set; }
        public string Telefono { get; set; }
        public string CalleNumero { get; set; }
        public string CodigoPostal { get; set; }
        public Nullable<int> ColoniaID { get; set; }
        public Nullable<int> EstatusRegistroID { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public System.Guid CorporativoID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catBusquedaCentro> catBusquedaCentro { get; set; }
        public virtual catLicencia catLicencia { get; set; }
        public virtual catTipoCentro catTipoCentro { get; set; }
        public virtual tblCorporativo tblCorporativo { get; set; }
    }
}
