//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelimundoERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuariosEmpresa
    {
        public int UsuariosEmpresaID { get; set; }
        public Nullable<System.Guid> UsuarioID { get; set; }
        public Nullable<System.Guid> EmpresaID { get; set; }
    
        public virtual tblEmpresa tblEmpresa { get; set; }
        public virtual tblUsuarios tblUsuarios { get; set; }
    }
}
